### ISSUE TITLE
target world not loaded???

### ISSUE THREAD

**Issue by Bidou0418** [ProjectInfinity/LeetTP-PocketMine#1]
once i set a home or warp and try to go back to those locations i get Target world Not loaded message...

**Comment by ProjectInfinity** [comment]
The world your home/warp is in either doesn't exist anymore or you changed it's name.

**Comment by Bidou0418** [comment]
Thats not possible.
i have 1 world and all i did was setwarp 1 and sethome 1, then warp 1 and home 1.
my server runs genisys 1.1 dev 364

**Comment by Bidou0418** [comment]
The only possible explanation i can think of is the following;
My world map was generated with mcpc and was called new world, however my level name is world in my server properties.
Could this be what causes this message?
the setspawn command works fine

**Comment by Bidou0418** [comment]
all fixed
it was a world name issue
