### ISSUE TITLE
Teleporting warp bug

### ISSUE THREAD

**Issue by Mike4l6** [ProjectInfinity/LeetTP-PocketMine#2]
If I try to warp to a different world it will put up this [22:21:51] critical> Unhandled exception executing command 'warp Tower1Easy' in warp: Call to a member function getName() on null
[22:21:51] critical> Error: "Call to a member function getName() on null" (EXCEPTION) in "/LeetTP.phar/src/Leet/LeetTP/command/warp/WarpCommand" at line 102
 it will also happen if I teleport to another world and try to warp to the warp

**Comment by ProjectInfinity** [comment]
But it works in the default world?

**Comment by Mike4l6** [comment]
Yes but not when I teleport to another world and try to warping to a warp in another world while in the same world but not the default world

**Comment by ProjectInfinity** [comment]
Are you sure the world is loaded?

**Comment by Mike4l6** [comment]
No its not load but isn't it suppose to load the world?

**Comment by ProjectInfinity** [comment]
No. Whatever multi world plugin you are using should be automatically
loading worlds you have configured it to. That's the logical way.

**Comment by Mike4l6** [comment]
Other warp plugins load the world why doesn't yours?

**Comment by Mike4l6** [comment]
Well I used a another warp alternative so yeah I can warp from world to
world and the one I'm using works but yours doesn't it has a error...

**Comment by ProjectInfinity** [comment]
Mine works, it just needs a multi-world plugin that isn't crap. If you don't understand the implications of auto-loading a world when a user wants to teleport to it... That's okay.

**Comment by Mike4l6** [comment]
I don't have a bad multi-world plugin by the way ( Many - Worlds ) And its
called an error

**Comment by ProjectInfinity** [comment]
That's a bad multi-world plugin. It should have a configuration where you set which worlds it should load on startup.

**Comment by Mike4l6** [comment]
What I'm saying is that its not the multi world plugin thats making its bug
because I LOADED the world and try to warp at the same world's warp and it
got an error ( I used a another plugin called EssentialsPE ) My plugin even
loads unloaded ones so I don't know whats wrong with your plugin , but
anyways if you don't think I understand than ok...
